### PR TITLE
3.2 branch Descriptive Statistics notebook

### PR DESCRIPTION
**Pull request by aalvar23**
I checked the Descriptive statistics notebook with Stephen, and he approved!

### CODE REVIEW

**Comment by bsipocz** [comment]
Thank you @aalvar23 for the pull request. There are some rendering issues with the equations, otherwise, it all looks good. In fact, the sizing of the figures looks better than the rest of the notebooks, we'll have to check the differences and adjust those others accordingly.

**Comment by aalvar23** [comment]
No problem! My last commit should fix all the rendering issues.

**Comment by bsipocz** [comment]
Thank you, you've been quicker than I could have posted the line-level review. Thanks!

**Review by bsipocz — APPROVED** [review]
This all looks good now, thank you!

And thank you @stephenportillo for the content review!

**Pull request merged**
